apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-sdn-hub-backend
  namespace: learn-sdn-hub
  labels:
    app.kubernetes.io/instance: learn-sdn-hub-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: learn-sdn-hub-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: learn-sdn-hub
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: learn-sdn-hub-backend
    spec:
      containers:
      - name: learn-sdn-hub-backend
        # image: ghcr.io/prona-p4-learning-platform/learn-sdn-hub-backend:254-feature-k8s-docker-images
        image: learn-sdn-hub-backend:latest
        imagePullPolicy: IfNotPresent
        
        args:
          - "-t"
          - "localmultiuservm"
          - "-p"
          - "80"
          - "-a"
          - "10.0.0.10"
          - "-s"
          - "22"
          - "-u"
          - "p4"
          - "-w"
          - "p4"
          - "-b"
          - "p4:p4"
          - "-m"
          - "p4:0"

        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 80
