apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-sdn-hub-frontend
  namespace: learn-sdn-hub
  labels:
    app.kubernetes.io/instance: learn-sdn-hub-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: learn-sdn-hub-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: learn-sdn-hub
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: learn-sdn-hub-frontend
    spec:
      containers:
      - name: learn-sdn-hub-frontend
        # image: ghcr.io/prona-p4-learning-platform/learn-sdn-hub-frontend:254-feature-k8s-docker-images
        image: learn-sdn-hub-frontend:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 80
