apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learn-sdn-hub-frontend-ingress
  namespace: learn-sdn-hub
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
spec:
  ingressClassName: nginx

  tls:
  - hosts:
      - prona.local
    secretName: prona-local-tls

  rules:
  - host: prona.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: learn-sdn-hub-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: learn-sdn-hub-backend
            port:
              number: 80
