apiVersion: v1
kind: Service
metadata:
  name: learn-sdn-hub-backend
  namespace: learn-sdn-hub
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: learn-sdn-hub-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
