apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-sdn-hub-backend
  namespace: learn-sdn-hub
  labels:
    app.kubernetes.io/instance: learn-sdn-hub-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: learn-sdn-hub-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: learn-sdn-hub
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: learn-sdn-hub-backend
    spec:
      containers:
      - name: learn-sdn-hub-backend
        image: nginx # add backend image here
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 80
