apiVersion: v2
name: learn-sdn-hub
description: A Helm chart for Learn SDN Hub with dependencies
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Ingress Controller
  - name: ingress-nginx
    version: 4.14.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled

  # Cert Manager
  - name: cert-manager
    version: 1.19.0
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled

  - name: flux2
    version: 2.13.0
    repository: https://fluxcd-community.github.io/helm-charts
    condition: fluxcd.enabled

  - name: mongodb
    version: 14.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enable