apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  user: {{ .Values.mongodb.credentials.username | b64enc }}
  password: {{ .Values.mongodb.credentials.password | b64enc }}
  user-express: {{ .Values.mongodb.credentials.username | b64enc }}
  password-express: {{ .Values.mongodb.credentials.password | b64enc }}