apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  user: YWRtaW4= # admin
  password: cGFzc3dvcmQ=  # "password"   # not safe
  user-express: YWRtaW4=
  password-express: cGFzc3dvcmQ=