apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-express
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-mongo-express
  ports:
    - name: http
      port: 80
      targetPort: 8081
