apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongodb
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: {{ .Values.mongodb.service.port }}
        args:
          - "--bind_ip_all"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-secret
              key: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-secret
              key: password
        volumeMounts:
        - name: mongo-pvc
          mountPath: /data/db
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - mongosh "mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@127.0.0.1:27017/admin" --eval "db.adminCommand('ping')" >/dev/null 2>&1
          initialDelaySeconds: 5
          periodSeconds: 3
  volumeClaimTemplates:
  - metadata:
      name: mongo-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mongodb.ressources.requests.storage }}