name: Build and Push Docker Frontend Image

on:
  push:
    branches: [ "254-feature/k8s/docker-images" ]
    # optional
    # tags: [ 'v*.*.*' ]
  # workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: learn-sdn-hub-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # important for the push to ghcr.io
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # QEMU is needed for emulation from ARM64 to AMD64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # GitHub Container Registry login
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # generate tags
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      # build and push
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          # push: ${{ github.event_name != 'pull_request' }}
          # defining platform
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
